name: medical-intake-chatbot
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/medical-intake-chatbot
  health_check:
    http_path: /twilio_start_bot
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs
  run_command: uvicorn bot_runner:app --host 0.0.0.0 --port $PORT
  envs:
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DAILY_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ELEVENLABS_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ELEVENLABS_VOICE_ID
    scope: RUN_TIME
    type: SECRET
  - key: TWILIO_ACCOUNT_SID
    scope: RUN_TIME
    type: SECRET
  - key: TWILIO_AUTH_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: TWILIO_PHONE_NUMBER
    scope: RUN_TIME
    type: SECRET
  - key: SENDGRID_API_KEY
    scope: RUN_TIME
    type: SECRET 